### ISSUE TITLE
Requirement is pinned for aioazuredevops 1.3.4: click==7.1.2

### ISSUE THREAD

**Issue by MartinHjelmare** [timmo001/aioazuredevops#1]
# Description
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

## How to reproduce the issue (if applicable)
```
(home-assistant) x:~/Dev/home-assistant/home-assistant$ pip install -r requirements_all.txt
...
(home-assistant) x:~/Dev/home-assistant/home-assistant$ pipdeptree --reverse --packages click
...
click==7.1.1
  - aioazuredevops==1.3.4 [requires: click==7.1.2]
...
```

**Comment by timmo001** [comment]
Unpinned requirements and published a new version to PyPi :+1:
